name: fcfs-monkeys
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - matplotlib
  - seaborn
  - pylint >=2.14.4
  - pip
  - pip:
    - ipdb
    - rangetree
    - ordered-set
    - nltk
